# Generated by Django 2.2.1 on 2019-10-13 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='time_upload',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time'),
        ),
    ]
